using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PauseMenu : MonoBehaviour
{

    public GameObject PausePanel;

    public void Pause()
    {
        PausePanel.SetActive(true);
        Time.timeScale = 0;

        // ðŸ”‡ PAUSAR MÃšSICA
        MusicManager.instance.PauseMusic();
    }

    public void Continue()
    {
        PausePanel.SetActive(false);
        Time.timeScale = 1;

        // ðŸŽµ REANUDAR MÃšSICA
        MusicManager.instance.ResumeMusic();
    }

    public void Quit()
    {
        PausePanel.SetActive(false);
        Time.timeScale = 1;

        // ðŸŽµ REANUDAR MÃšSICA (si vuelves al menÃº)
        MusicManager.instance.ResumeMusic();

        SceneManager.LoadSceneAsync(0);
    }

    public void Restart()
    {
        PausePanel.SetActive(false);
        Time.timeScale = 1;

        // ðŸŽµ REANUDAR MÃšSICA EN EL REINICIO
        MusicManager.instance.ResumeMusic();

        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    void Start() { }

    void Update() { }
}
